"""
Implementation of a class generating random graphs using two methods:
    - Erdos'
    - Scale free generation
"""

from networkx import erdos_renyi_graph, scale_free_graph
from networkx import pagerank

class Random_Graph_Generator():
    
    def __init__(
            self, 
            graph_type: str,
    ) -> None:
        """
        Initialization method

        Parameters
        ----------
        graph_type : string
            Defines the type of graph generated by an
            implementation of the Random_Graph_Generator
            class
        """
        # Defines the generator function
        if graph_type.lower() == "erdos":
            print("Erdos Graph Generator declared")
            self.type            = "e"
            self.graph_generator = erdos_renyi_graph
        else:
            print("Scale-Free Graph Generator declared")
            self.type            = "s"
            self.graph_generator = scale_free_graph
        # Defines the placeholders
        self.graphs              = None
        self.page_ranks          = None
            
    def graphs_generate(
            self, 
            m: int, 
            n: int, 
            p: float = None
    ) -> None:
        """
        Generator method. Produces m graphs of n nodes
        with edges with probability p (in the case of
        Erdos' method).

        Parameters
        ----------
        m : integrer
            Number of graphs generated
        n : integer
            Number of nodes in each graph
        p : float, optional
            Probability for edge creation
        """
        if self.type == "e":
            args    = (n, p)
        else:
            args    = (n, )
        self.graphs = [self.graph_generator(*args) 
                       for _ in range(m)]
    
    def graphs_page_rank_compute(
            self, 
            alpha: float = 0.85
    ) -> None:
        """
        Given a set of generated graphs stored in the
        self.graphs attributes, computes each graph's
        PageRank value

        Parameters
        ----------
        alpha : float, optional
            Damping parameter for PageRank, default=0.85.
        """
        self.page_ranks = [pagerank(g, alpha) 
                           for g in self.graphs]
    
    def graphs_retrieve(self) -> tuple:
        """
        Returns the generated graphs and their respective
        PageRank values in the shape of a X, y tuple.
        """
        return (self.graphs, self.page_ranks)
        